export const products = [
  {
    slug: "heritage-ceket",
    name: "Heritage Deri Ceket",
    kategori: "ceket",
    material: "Çocuk dostu premium deri",
    price: "₺1.890",
    badge: "Çok Satan",
    colors: ["#3d2b1f", "#8b4f2d", "#c5a881"],
    img: "/images/product-1.jpg",
    gallery: ["/images/product-1.jpg", "/images/category-ceket.jpg", "/images/featured-jacket.jpg"],
    offset: false,
  },
  {
    slug: "moto-ceket",
    name: "Moto Deri Ceket",
    kategori: "ceket",
    material: "Çocuk dostu premium deri",
    price: "₺2.190",
    badge: null,
    colors: ["#f4a7b9", "#3d2b1f"],
    img: "/images/category-ceket-kiz.jpg",
    gallery: ["/images/category-ceket-kiz.jpg", "/images/product-2.jpg", "/images/hero.jpg"],
    offset: true,
  },
  {
    slug: "classic-yelek",
    name: "Classic Deri Yelek",
    kategori: "yelek",
    material: "Çocuk dostu premium deri",
    price: "₺1.290",
    badge: null,
    colors: ["#e07020", "#8b4f2d"],
    img: "/images/product-3.jpg",
    gallery: ["/images/product-3.jpg", "/images/category-yelek.jpg", "/images/brand-story.jpg"],
    offset: false,
  },
  {
    slug: "street-sneaker",
    name: "Street Kid Sneaker",
    kategori: "ayakkabi",
    material: "Deri detaylı sneaker · EU 28–37",
    price: "₺890",
    badge: "Yeni",
    colors: ["#dbdad7", "#8b4f2d", "#1a1a1a"],
    img: "/images/product-4.jpg",
    gallery: ["/images/product-4.jpg", "/images/category-ayakkabi.jpg", "/images/lifestyle-1.jpg"],
    offset: true,
  },
  {
    slug: "biker-yelek",
    name: "Biker Deri Yelek",
    kategori: "yelek",
    material: "Çocuk dostu premium deri",
    price: "₺1.390",
    badge: null,
    colors: ["#1a1a1a", "#3d2b1f"],
    img: "/images/brand-story.jpg",
    gallery: ["/images/brand-story.jpg", "/images/category-yelek.jpg", "/images/atelier.jpg"],
    offset: false,
  },
  {
    slug: "palet-sneaker",
    name: "Palet Sneaker",
    kategori: "ayakkabi",
    material: "Deri detaylı sneaker · EU 28–37",
    price: "₺990",
    badge: null,
    colors: ["#dbdad7", "#c5a881"],
    img: "/images/lifestyle-2.jpg",
    gallery: ["/images/lifestyle-2.jpg", "/images/lifestyle-1.jpg", "/images/category-ayakkabi.jpg"],
    offset: true,
  },
];

export type Product = typeof products[0];
