import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#dbdad7",
        "inverse-on-surface": "#f2f1ee",
        "primary-fixed": "#ffdbca",
        "background": "#faf9f6",
        "primary-fixed-dim": "#ffb690",
        "error-container": "#ffdad6",
        "outline": "#85736b",
        "secondary-container": "#fed3c7",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#e7bdb1",
        "on-background": "#1a1c1a",
        "on-tertiary-fixed": "#281801",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#53443c",
        "on-surface": "#1a1c1a",
        "inverse-primary": "#ffb690",
        "secondary-fixed": "#ffdbd0",
        "outline-variant": "#d8c2b8",
        "inverse-surface": "#2f312f",
        "tertiary": "#725a39",
        "surface-tint": "#8b4f2d",
        "surface-container-low": "#f4f3f1",
        "on-tertiary-container": "#513d1e",
        "surface-container-highest": "#e3e2e0",
        "on-primary-fixed": "#331100",
        "surface-bright": "#faf9f6",
        "on-primary-container": "#663212",
        "on-secondary-fixed-variant": "#5d4037",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#584324",
        "surface-container": "#efeeeb",
        "on-secondary-fixed": "#2c160e",
        "surface": "#faf9f6",
        "tertiary-fixed": "#feddb3",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#e1c299",
        "primary": "#8b4f2d",
        "on-secondary-container": "#795950",
        "secondary": "#77574d",
        "primary-container": "#e69b73",
        "tertiary-container": "#c5a881",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-container-high": "#e9e8e5",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#6e3818",
        "surface-variant": "#e3e2e0",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Epilogue", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
